### ISSUE TITLE
References for bicubic implementation

### ISSUE THREAD

**Issue by nanangarsyad** [Ace-0/Bicubic-Interpolation#1]
May I know what references you're using to implements the bicubic algorithm?
Maybe the formula being used or references for it?

Thank you

**Comment by Ace-0** [comment]
It is base on a paper I have read and some references on the internet.
The title of the paper is "Cubic Convolution Interpolation for Digital Image
Processing" and I still have the pdf file.
If you want to read the paper I am happy to send it to you.

**Comment by Ace-0** [comment]
It is base on a paper I have read and some references on the internet.
The title of the paper is "Cubic Convolution Interpolation for Digital Image
Processing" and I still have the pdf file.
If you want to read the paper I am happy to send it to you.

**Comment by nanangarsyad** [comment]
Thank you for the kind response.
If it's not causing you any more inconvenience please do send me the paper. 
I want to make sure that I also read the same paper as you do.

**Comment by Ace-0** [comment]
But I don't have your email address yet :-)

**Comment by nanangarsyad** [comment]
Oh, here's it.
_deleted_ _at_gmail.com, (sorry, I delete the email)

Thank you.
